// <auto-generated />
namespace Powerlevel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Gender3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gender3));
        
        string IMigrationMetadata.Id
        {
            get { return "201902120244064_Gender3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
